### ISSUE TITLE
Example passthru not detected under Linux (Bitwig demo).

### ISSUE THREAD

**Issue by perlindgren** [RustAudio/vst3-sys#2]
Hi Folks
I'm playing around a bit with the vst3-sys. The example compiled ok, but I fail to get Bitwig to recognize the plugin. (I'm under arch, I have local plugins in ~/.vst3 (added to Bitwig), copied the generated libpassthru.so there, but Bitwig seems not to pick it up.) Compiled in release mode.

/Per

**Comment by perlindgren** [comment]
I tried compiling the vst-rs example and they are detected by Bitwig. In order to make sure its not exclusively a Bitwig issue I tired with Reaper as well (and the same behavior was detected), vst-rs plugins detected but not the vst3/passthrough.

Next up would be to try the vst3 validator by Steinberg.

**Comment by m-hilgendorf** [comment]
Thanks for trying the crate out! 

This is known, the crate is a work in progress. The example plugin doesn't instantiate yet in the validator and there are some issues with IID endianness on Linux that haven't been figured out. 

As well, vst3 plugins are not distributed as shared objects, you need to package it into a directory structure 

     /passthru.vst3/Contents/x86_64-linux/passthru.so 

There's a bit of work left before getting it to load in a host and pass audio, we're not there yet.

**Comment by MirkoCovizzi** [comment]
@perlindgren Can you try the `again` plugin? It should work on Linux.

**Comment by m-hilgendorf** [comment]
@perlindgren should be resolved!
